apiVersion: apps/v1
kind: Deployment
metadata:
  name: aladin-web-deployment
  namespace: default
  labels:
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aladin-web
  template:
    metadata:
      labels:
        app: aladin-web
    spec:
      containers:
      - name: aladin
        image: 535954374321.dkr.ecr.ap-northeast-2.amazonaws.com/aladin:f274525c
        ports:
        - containerPort: 80