apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: aladin-web-hpa
  namespace: default
spec:
  minReplicas: 3
  maxReplicas: 100
  targetCPUUtilizationPercentage: 30
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: aladin-web-deployment