apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: aladin-web-hpa
  namespace: default
spec:
  # Scale할 Deployment 설정
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: aladin-web-deployment
  minReplicas: 3
  maxReplicas: 100

  # Scale할 조건
  metrics:
  - resource:
      name: cpu
      targetAverageUrilization: 5
    type: Resource